### ISSUE TITLE
How to add context attributes

### ISSUE THREAD

**Issue by danielgomezrico** [la-haus/flutter-segment#23]
How can we add context hash for events?

# event json example
```json
{
  "context": {
      // This one
   },
  
  "properties": {},
}
```

# Docs
Context docs: https://segment.com/docs/connections/spec/common/#context

- Android: https://segment.com/docs/connections/sources/catalog/libraries/mobile/android/#context
- iOS: ????

**Comment by ariefwijaya** [comment]
I think we already have it [here](https://github.com/la-haus/flutter-segment#sending-device-tokens-strings-for-push-notifications). is this not enough?

**Comment by danielgomezrico** [comment]
:O it does work, thanks for the message
