### ISSUE TITLE
Google Play policies violation in flutter_segment 3.7.0

### ISSUE THREAD

**Issue by vbuberen** [la-haus/flutter-segment#30]
After pushing another update for the app I am currently working on I saw the following warning in Play Developer Console:

> The following SDK versions are non compliant with Google Play policies:
> 
> com.segment.analytics.android:analytics:4.10.0
> The SDK collects personal or sensitive data that includes but may not be limited to Advertising ID, Android ID identifiers. Persistent device identifiers may not be linked to other personal and sensitive user data or resettable device identifiers as described in the [User Data](https://support.google.com/googleplay/android-developer/answer/10144311) policy.
> 
> Starting from August 9, 2022 midnight (UTC), new app releases containing the SDK version(s) that do not comply with the [User Data](https://support.google.com/googleplay/android-developer/answer/10144311) policy will be blocked from release. You may consider moving to another SDK; removing this SDK; or if available from your SDK provider, upgrading to a policy-compliant version of this SDK that does not include the violating code.
> 
> According to the information provided by your SDK provider, you may consider upgrading to4.10.1. Please consult the SDK provider for further information.
> 
> Read through the [User Data](https://support.google.com/googleplay/android-developer/answer/10144311) policy for more details, and how to submit an updated app for review [here](https://support.google.com/googleplay/android-developer/answer/2477981%20#resubmit).
> 
> If you've reviewed the policy and feel our decision may have been in error, please reach out to our [policy support team](https://support.google.com/googleplay/android-developer/contact/appwarning?ts=sdk).

Checked the Segment Android SDK and saw that in 4.10.1 the issue was resolved: https://github.com/segmentio/analytics-android/blob/master/CHANGELOG.md#version-4101-jan-11-2022

Considering that 9th of August is pretty soon already and release cycle of `flutter_segment` isn't that short, it is worth to update the Segment Android SDK and release an update for the `flutter_segment`.

Issues occurs with `flutter_segment 3.7.0`

P.S. I will open a PR with needed changes.

**Comment by danielgomezrico** [comment]
@vbuberen have you checked your app data checks? You need to specify there when your app does get or not user data and then that will not fail, I think that this is the issue because we haven't seen this problem in production.

**Comment by vbuberen** [comment]
Yes, the corresponding section in the Play Store is filled correctly. This warning appeared just yesterday with a new release. 
I shared the whole content of a message from the Developer Console, which clearly indicates that this is because of `4.10.0` version of `com.segment.analytics.android:analytics`. In the PR I opened I mentioned that the suggested by Google Play version `4.10.1` indeed has the fix for the issue. Here is the PR in that Android Segment repo, which even has corresponding title: https://github.com/segmentio/analytics-android/pull/781

**Comment by ariefwijaya** [comment]
Confirmed, just got it too 
![image](https://user-images.githubusercontent.com/24664153/172978357-4962a16c-f1be-4b58-b195-62721ada46b4.png)

**Comment by ariefwijaya** [comment]
Confirmed, just got it too 
![Screenshot_2022-06-10_at_09 19 44](https://user-images.githubusercontent.com/24664153/172980265-8579a865-ed1f-42da-b855-354a29c0b554.png)

**Comment by AkshitOstwal** [comment]
I also have same message coming on play store, I hope #31 will get merged soon.

**Comment by MuzavaziTawa** [comment]
Facing the same problem, seems they are actually enforcing it now though because i cant publish my app on Google Play Store

**Comment by danielgomezrico** [comment]
I will reopen to wait until someone says that this worked, related to: https://github.com/la-haus/flutter-segment/pull/31#issuecomment-1153920705

**Comment by tspoke** [comment]
I was able to deploy to Google Play with **success** using the latest commit with the fix : 

```
flutter_segment:
    git:
      url: https://github.com/la-haus/flutter-segment
      ref: 4db18e9
```

LGTM 👍

**Comment by TejasShuklaWeserveCodes** [comment]
Google Play policies violation in flutter_segment 3.7.0 

Your app includes non compliant SDK version
Your app ********** version code 1 includes SDK com.segment.analytics.android:analytics, 4.10.0 or an SDK that one of your libraries depends on, which collects personal or sensitive data that includes but may not be limited to Advertising ID, Android ID identifiers. Persistent device identifiers may not be linked to other personal and sensitive user data or resettable device identifiers as described in the User Data policy.

Starting from August 9, 2022 midnight (UTC), new app releases containing the SDK version(s) that do not comply with the User Data policy will be blocked from release. You may consider moving to another SDK; removing this SDK; or if available from your SDK provider, upgrading to a policy-compliant version of this SDK that does not include the violating code.

According to the information provided by your SDK provider, you may consider upgrading to 4.10.1. Please consult the SDK provider for further information.
Learn more
Read through the User Data policy for more details, and how to submit an updated app for review here.
If you've reviewed the policy and feel our decision may have been in error, please reach out to our policy support team.
Learn More
Dismiss
Error

Note: We have also downloaded the segment plugin and use it in our app but we are still facing the same problem. 

![Screenshot_15_06_2022](https://user-images.githubusercontent.com/72876637/173821746-739e0cbd-5f55-4fa9-80ab-91610196e157.png)

**Comment by tspoke** [comment]
@TejasShukalPlutustec It has already been fixed in flutter_segment 3.9.0.

**Comment by ariefwijaya** [comment]
why don't we close this issue to avoid misunderstanding ?

**Comment by vbuberen** [comment]
Also believe that it can be closed based on feedback provided above.

For those, who scroll to the end of issues right away the solution is to update `flutter_segment` to `3.9.0`
