### ISSUE TITLE
Non compliant SDK version android.analytics error

### ISSUE THREAD

**Issue by MuzavaziTawa** [la-haus/flutter-segment#34]
Hello there. Tried uploading a new app version to Google play store and received this error:

"Your app xxx.xx.xxx.xx version code 1 includes SDK com.segment.analytics.android:analytics, 4.10.0 or an SDK that one of your libraries depends on which collects personal or sensitive data that includes but may not be limited to Advertising ID, Android ID identifiers. Persistent device identifiers may not be linked to other personal and sensitive user data or resettable device identifiers as described in the user data policy.

Starting from 9 August 2022 midnight (UTC), new app releases containing SDK versions that do not comply with the User data policy will be blocked from release ......According to the information provided by your SDK provider, you may consider upgrading to 4.10.1. Please consult the SDK provider for further information"

I have the latest version flutter_segment: 3.7.0. The screenshot shows the build.gradle file inside flutter_segment: 3.7.0.

Please help! URGENT

![Screenshot 2022-06-13 at 15 50 03](https://user-images.githubusercontent.com/45089777/173373786-c78ea769-fe6f-4e3b-93c5-aaf03598a04b.png)

**Comment by danielgomezrico** [comment]
Duplicated from: https://github.com/la-haus/flutter-segment/issues/30

**Comment by MuzavaziTawa** [comment]
Yes, sorry. I saw #30 after I had already raised the issue. Will follow the issue from there.
