### ISSUE TITLE
Important warning in Google Play Console

### ISSUE THREAD

**Issue by konoshenko** [la-haus/flutter-segment#40]
Can someone explain what currently I should do with my app for solving this problem?

 flutter_segment: ^3.5.0
<img width="974" alt="Screenshot 2022-06-28 at 14 58 00" src="https://user-images.githubusercontent.com/102408516/176173192-cc2dfcd9-1ecf-4388-b27a-7e5e1a9d1dbc.png">

**Comment by danielgomezrico** [comment]
@konoshenko Maybe this fix your issue? https://github.com/la-haus/flutter-segment/issues/30 

Update to `3.9.0`

**Comment by konoshenko** [comment]
@danielgomezrico Thank you for help 😊

**Comment by Pexeed** [comment]
I'm using 3.9.0 and got this error again on today's build, we probably need to update the Android SDK again in the library.

> Publishing failed :| Google Play failed to upload artefacts. Your artifact (version code 1560) contains an SDK (com.segment.analytics.android:analytics) with version 4.10.0 that collects personal or sensitive data that includes but may not be limited to Advertising ID, Android ID identifiers. Persistent device identifiers may not be linked to other personal and sensitive user data or resettable device identifiers as described in the User Data policy: https://support.google.com/googleplay/android-developer/answer/10144311. To be allowed to publish, you may consider upgrading to 4.10.1 which the SDK provider has recommended for use instead. Please consult the SDK provider for further information.Read through the User data policy: https://support.google.com/googleplay/android-developer/answer/10144311 policy for more details, and how to submit an updated app for review here: https://support.google.com/googleplay/android-developer/answer/2477981#resubmit. If you've reviewed the policy and feel our decision may have been in error, please reach out to our policy support team: https://play.google.com/console/appealsForm?aid=io.floatme.floatmeapp&ts=SR. For more information see https://support.google.com/googleplay/android-developer/answer/10358880.: { "error": { "code": 403, "message": "Your artifact (version code 1560) contains an SDK (com.segment.analytics.android:analytics) with version 4.10.0 that collects personal or sensitive data that includes but may not be limited to Advertising ID, Android ID identifiers. Persistent device identifiers may not be linked to other personal and sensitive user data or resettable device identifiers as described in the User Data policy: https://support.google.com/googleplay/android-developer/answer/10144311. To be allowed to publish, you may consider upgrading to 4.10.1 which the SDK provider has recommended for use instead. Please consult the SDK provider for further information.Read through the User data policy: https://support.google.com/googleplay/android-developer/answer/10144311 policy for more details, and how to submit an updated app for review here: https://support.google.com/googleplay/android-developer/answer/2477981#resubmit. If you've reviewed the policy and feel our decision may have been in error, please reach out to our policy support team: https://play.google.com/console/appealsForm?aid=io.floatme.floatmeapp&ts=SR. For more information see https://support.google.com/googleplay/android-developer/answer/10358880.", "status": "PERMISSION_DENIED" } }

**Comment by danielgomezrico** [comment]
The mesage you show is weird, the version the library use is not that one, is https://github.com/la-haus/flutter-segment/blob/master/android/build.gradle#L37

**Comment by Pexeed** [comment]
Ok found out what happened, we merged a dependabot PR that moved the segment version back, my bad, nothing to see here lol
