### ISSUE TITLE
Update AppsFlyer SDK

### ISSUE THREAD

**Issue by luizpaulofranz** [la-haus/flutter-segment#69]
We are using `flutter-segment` here and we also added `appsflyer_sdk ` package on the project to directly handle some appsFlyer events. Now we are getting conflicts on Native Appsflyer SDK versions.

I would suggest upgrade the AppsFlyer SDK version here on `flutter-segment` package.

```
[!] CocoaPods could not find compatible versions for pod "AppsFlyerFramework":
  In Podfile:
    appsflyer_sdk (from `.symlinks/plugins/appsflyer_sdk/ios`) was resolved to 6.8.0, which depends on
      AppsFlyerFramework (= 6.9.1)

    flutter_segment (from `.symlinks/plugins/flutter_segment/ios`) was resolved to 3.12.1, which depends on
      segment-appsflyer-ios (= 6.8.0) was resolved to 6.8.0, which depends on
        segment-appsflyer-ios/Main (= 6.8.0) was resolved to 6.8.0, which depends on
          AppsFlyerFramework (~> 6.8.0)
```

**Comment by iaasthatech** [comment]
[We are facing the same issue. ](https://github.com/la-haus/flutter-segment/pull/70)

have raised this PR
