### ISSUE TITLE
How to configure AppsFlyer on Segment?

### ISSUE THREAD

**Issue by luizpaulofranz** [la-haus/flutter-segment#72]
I saw that we have a `SegmentConfig` called `appsflyerIntegrationEnabled`, but I could not see where to add AppsFlyer specific params, like `devKey`.

So, what does this field `appsflyerIntegrationEnabled=true` do?

ps: I try to read the native codes, but I am not versed on the native platforms, and I did not find any reference for this field on the docs.

**Comment by danielgomezrico** [comment]
@luizpaulofranz It enables the apps flyer integration from segment, take a look to this doc: 
- https://segment.com/docs/connections/destinations/catalog/appsflyer/ 
- https://github.com/AppsFlyerSDK/appsflyer-segment-android-plugin

**Comment by Imgkl** [comment]
@danielgomezrico  Am I required to do all the native setups as well or just the boolean would suffice granted I have appsflyer destination enabled on segment?

**Comment by ahmet-fennel** [comment]
Hi @Imgkl were you able to figure out if the boolean value is enough
